### PR TITLE
Fix accessibility instructions contrast on light backgrounds

### PR DESCRIPTION
**Pull request by hkamran80**
Old versus new
<div style="display:flex;justify-content:center;">
Screenshot 2023-02-03 at 11 19 10 PM

Screenshot 2023-02-03 at 11 38 50 PM
</div>

### CODE REVIEW

**Comment by aheze** [comment]
Nice, thanks. Could you also add a screenshot of light mode just to confirm?

**Comment by hkamran80** [comment]
Sure thing

**Comment by hkamran80** [comment]
Screenshot 2023-02-03 at 11 55 09 PM

**Comment by aheze** [comment]
Didn't even know the [`contrast`](https://developer.apple.com/documentation/swiftui/view/contrast(_:)) modifier existed, thanks!

**Comment by hkamran80** [comment]
> Didn't even know the [`contrast`](https://developer.apple.com/documentation/swiftui/view/contrast(_:)) modifier existed, thanks!

I learned about it after looking at the related topics of the `brightness` modifier in Apple's docs

**Pull request merged**
