### PR TITLE
Update ZIP file URL

### PR DESCRIPTION
**Pull request by hkamran80**

### CODE REVIEW

**Comment by aheze** [comment]
Thanks!

**Comment by muescha** [comment]
did you need still this file - or is it obsolete? 
https://github.com/aheze/Squirrel/blob/main/Squirrel.zip

**Comment by hkamran80** [comment]
> did you need still this file - or is it obsolete? [`https://github.com/aheze/Squirrel/blob/main/Squirrel.zip`](https://github.com/aheze/Squirrel/blob/main/Squirrel.zip?rgh-link-date=2023-02-05T04%3A29%3A42Z)

It's obsolete now

**Comment by muescha** [comment]
i have no access to the repo - someone (@aheze) should remove this zip to avoid confusion...

**Comment by hkamran80** [comment]
> i have no access to the repo - someone (@aheze) should remove this zip to avoid confusion...

Make a PR that removes it

**Pull request merged**
